#cloud-config
autoinstall:
  version: 1
  
  # 1. Configuração de Localidade e Teclado
  locale: pt_BR.UTF-8
  keyboard:
    layout: br

  # 2. Configuração de Repositórios e Chaves GPG (Inline para evitar erros de download)
  apt:
    preserve_sources_list: false
    sources:
      anydesk.list:
        source: "deb https://deb.anydesk.com all main"
        key: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          mQGNBF3p39wBDADWvV8Y6fGvX9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9
          mQGNBF3p39wBDADWvV8Y6fGvX9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9
          # [Nota: Substitua este bloco pelo conteúdo real da chave AnyDesk]
          -----END PGP PUBLIC KEY BLOCK-----
      google-chrome.list:
        source: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        key: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          mQENBFU3h4EBCADfV9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9
          # [Nota: Substitua este bloco pelo conteúdo real da chave Google]
          -----END PGP PUBLIC KEY BLOCK-----
      dbeaver.list:
        source: "deb https://dbeaver.io/debs/dbeaver-ce /"
        key: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          mQENBFU3h4EBCADfV9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9
          # [Nota: Substitua este bloco pelo conteúdo real da chave DBeaver]
          -----END PGP PUBLIC KEY BLOCK-----
      vscode.list:
        source: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
        key: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          mQENBFU3h4EBCADfV9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9
          # [Nota: Substitua este bloco pelo conteúdo real da chave Microsoft]
          -----END PGP PUBLIC KEY BLOCK-----
      nodesource.list:
        source: "deb https://deb.nodesource.com/node_24.x nodistro main"
        key: |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          mQENBFU3h4EBCADfV9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9X9
          # [Nota: Substitua este bloco pelo conteúdo real da chave NodeSource]
          -----END PGP PUBLIC KEY BLOCK-----

  # 3. Instalação de Pacotes APT
  packages:
    - git
    - vim
    - wget
    - curl
    - apt-transport-https
    - ca-certificates
    - gnupg
    - dotnet-sdk-8.0
    - anydesk
    - google-chrome-stable
    - dbeaver-ce
    - code
    - nodejs

  # 4. Instalação de Snaps
  snaps:
    - name: postman
      channel: stable
    - name: rider
      channel: stable
      classic: true

  # 5. Comandos de Pós-Instalação (Docker e AD )
  late-commands:
    - curtin in-target -- sh -c "curl -fsSL https://get.docker.com | sh"
    - curtin in-target -- sh -c "usermod -aG docker \$(ls /home | head -n 1 )"
    - curtin in-target -- pam-auth-update --enable mkhomedir

  # 6. Seções Interativas (Permite escolher disco e criar usuário na hora)
  interactive-sections:
    - identity
    - storage
    - network
