#cloud-config
autoinstall:
  version: 1
  
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo" 
  
  packages:
    - git
    - vim
    - wget
    - curl
    - apt-transport-https
    - ca-certificates
    - gnupg
    - dotnet-sdk-8.0

  codecs:
    install: true
  drivers:
    install: true

  updates: all

  # 3. Instalação de Snaps
  snaps:
    - name: postman
      channel: stable
    - name: rider
      channel: stable
      classic: true

  # --- A MÁGICA PARA O MODO INTERATIVO ---
  # Estas linhas dizem ao instalador para NÃO automatizar estas telas
  interactive-sections:
    - identity
    - storage
    - network
